# Generated by Django 5.2.7 on 2025-11-04 16:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
