# Generated by Django 5.2.7 on 2025-11-04 19:20

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_content_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_description', models.TextField(blank=True, max_length=160, null=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('read_time', models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes')),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('trashed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trashed_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_description', models.TextField(blank=True, max_length=160, null=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('read_time', models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes')),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('author_name', models.CharField(blank=True, max_length=150)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('is_featured', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(blank=True, related_name='posts', to='blog.category')),
                ('trashed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trashed_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_date'],
            },
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
