# Generated by Django 5.2.7 on 2025-11-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_gmailtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='top_rated',
            field=models.BooleanField(default=False),
        ),
    ]
