# Generated by Django 5.2.7 on 2025-11-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_case_study_description_project_daily_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list, help_text="Enter technologies as a list, e.g., ['Python', 'Django', 'React']"),
        ),
    ]
