# Generated by Django 5.2.7 on 2025-11-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_project_tech_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
    ]
